import { Language, AppTranslations, EncryptionAlgorithm, AlgorithmOption } from './types';

export const APP_NAME = "KNOUX UltraEncrypt Pro";
export const AUTHOR_SIGNATURE = "Eng. Sadek elgazar";
export const KNOUX_LOGO_URL = "https://i.postimg.cc/NjNdMPvq/Chat-GPT-Image-Jun-7-2025-11-08-55-PM.png"; 
export const WHATSAPP_CONTACT = "0503281920";
export const EMAIL_CONTACT = "support@knoux7.com";
export const LOCATION_CONTACT = "Abu Dhabi, UAE";

export const DEFAULT_THEME = 'dark';
export const DEFAULT_LANGUAGE: Language = Language.English;

export const AVAILABLE_ALGORITHMS: AlgorithmOption[] = [
  { value: EncryptionAlgorithm.AES256_GCM, labelKey: 'algoAES256GCM' },
  { value: EncryptionAlgorithm.ChaCha20_Poly1305, labelKey: 'algoChaCha20Poly1305' },
  { value: EncryptionAlgorithm.NTRU, labelKey: 'algoNTRU', isPostQuantum: true },
  { value: EncryptionAlgorithm.Kyber, labelKey: 'algoKyber', isPostQuantum: true },
];

export const TRANSLATIONS: AppTranslations = {
  // General
  appName: { en: APP_NAME, ar: "KNOUX للتشفير الآمن برو" },
  loading: { en: "Loading...", ar: "جاري التحميل..." },
  search: { en: "Search...", ar: "بحث..." },
  save: { en: "Save", ar: "حفظ" },
  cancel: { en: "Cancel", ar: "إلغاء" },
  delete: { en: "Delete", ar: "حذف" },
  copy: { en: "Copy", ar: "نسخ" },
  copied: { en: "Copied!", ar: "تم النسخ!" },
  settings: { en: "Settings", ar: "الإعدادات" },
  theme: { en: "Theme", ar: "المظهر" },
  language: { en: "Language", ar: "اللغة" },
  lightTheme: { en: "Light", ar: "فاتح" },
  darkTheme: { en: "Dark", ar: "داكن" },
  english: { en: "English", ar: "الإنجليزية" },
  arabic: { en: "Arabic", ar: "العربية" },
  confirm: { en: "Confirm", ar: "تأكيد" },
  error: { en: "Error", ar: "خطأ" },
  success: { en: "Success", ar: "نجاح" },
  warning: { en: "Warning", ar: "تحذير" },
  close: { en: "Close", ar: "إغلاق" },
  path: { en: "Path", ar: "المسار" },
  status: { en: "Status", ar: "الحالة" },
  actions: { en: "Actions", ar: "إجراءات" },
  enabled: { en: "Enabled", ar: "مفعل" },
  disabled: { en: "Disabled", ar: "معطل" },
  general: { en: "General", ar: "عام" },
  operations: { en: "Operations", ar: "العمليات" },
  about: { en: "About", ar: "حول" },
  version: { en: "Version", ar: "الإصدار" },
  developedBy: { en: "Developed by", ar: "تطوير" },
  saved: { en: "Saved", ar: "تم الحفظ" },
  imported: { en: "Imported", ar: "تم الاستيراد" },
  successfully: { en: "Successfully", ar: "بنجاح" },
  settingsImportFailed: { en: "Settings import failed.", ar: "فشل استيراد الإعدادات." },
  settingsImportSuccess: { en: "Settings imported successfully!", ar: "تم استيراد الإعدادات بنجاح!"},
  taglineUltraEncrypt: { en: "Your Data, Your Control.", ar: "بياناتك تحت سيطرتك." },
  placeholderDefaultMessage: { en: "This section is under active development or awaiting content. Thank you for your patience!", ar: "هذا القسم قيد التطوير النشط أو في انتظار المحتوى. شكرا لك على صبرك!"},
  electronApiUnavailable: { en: "Feature not available: Electron API not found. Running in web mode?", ar: "الميزة غير متوفرة: واجهة Electron API غير موجودة. هل يعمل في وضع الويب؟"},
  
  // Sidebar
  dashboard: { en: "Dashboard", ar: "لوحة التحكم" }, 
  encrypt: { en: "Encrypt", ar: "تشفير" },
  decrypt: { en: "Decrypt", ar: "فك التشفير" },
  vaults: { en: "Vaults", ar: "الخزائن" },
  activityLog: { en: "Activity Log", ar: "سجل النشاط" },
  keyGenerator: { en: "Key Generator", ar: "مولد المفاتيح" },
  secureShredder: { en: "Secure Shredder", ar: "الحذف الآمن" },
  documentation: { en: "Documentation", ar: "التوثيق" }, 
  logout: { en: "Logout", ar: "تسجيل الخروج" },
  
  // Login Page
  loginPageTitle: { en: "KNOUX Secure Access", ar: "KNOUX الدخول الآمن" },
  loginWelcome: { en: "Welcome to KNOUX UltraEncrypt Pro", ar: "مرحباً بك في KNOUX للتشفير الآمن برو" },
  loginInstructions: { en: "Please log in to access your secure environment.", ar: "يرجى تسجيل الدخول للوصول إلى بيئتك الآمنة." },
  username: { en: "Username", ar: "اسم المستخدم" },
  enterUsername: { en: "Enter your username", ar: "أدخل اسم المستخدم الخاص بك" },
  loginButton: { en: "Login", ar: "تسجيل الدخول" },
  loginFailed: { en: "Login Failed", ar: "فشل تسجيل الدخول" },
  invalidCredentials: { en: "Invalid username or password. Please try again.", ar: "اسم المستخدم أو كلمة المرور غير صالحة. يرجى المحاولة مرة أخرى." },
  loginSuccess: { en: "Login Successful", ar: "تم تسجيل الدخول بنجاح" },
  welcomeBack: { en: "Welcome back, {0}!", ar: "مرحباً بعودتك، {0}!" },
  
  // Encrypt/Decrypt Pages
  encryptPageTitle: { en: "Secure File Encryption", ar: "تشفير آمن للملفات" },
  encryptPageSubtitle: { en: "Protect your sensitive data with robust, local encryption using industry-standard algorithms.", ar: "قم بحماية بياناتك الحساسة بتشفير محلي قوي باستخدام خوارزميات معتمدة." },
  selectFile: { en: "Select File", ar: "اختر ملف" },
  selectFiles: { en: "Select Files", ar: "اختر ملفات" },
  selectFolder: { en: "Select Folder", ar: "اختر مجلد" },
  selectOutputFolder: { en: "Select Output Folder", ar: "اختر مجلد الإخراج" },
  selectedFile: { en: "Selected File:", ar: "الملف المختار:" },
  selectedFiles: { en: "Selected Files:", ar: "الملفات المختارة:" },
  selectedFolder: { en: "Selected Folder:", ar: "المجلد المختار:" },
  outputFolder: { en: "Output Folder:", ar: "مجلد الإخراج:" },
  password: { en: "Password", ar: "كلمة المرور" },
  enterPassword: { en: "Enter password", ar: "أدخل كلمة المرور" },
  confirmPassword: { en: "Confirm Password", ar: "تأكيد كلمة المرور" },
  passwordsDoNotMatch: { en: "Passwords do not match!", ar: "كلمات المرور غير متطابقة!" },
  encryptionAlgorithm: { en: "Encryption Algorithm", ar: "خوارزمية التشفير" },
  selectAlgorithm: { en: "Select algorithm", ar: "اختر الخوارزمية" },
  encryptFile: { en: "Encrypt File", ar: "تشفير الملف" },
  decryptFile: { en: "Decrypt File", ar: "فك تشفير الملف" },
  encryptionInProgress: { en: "Encryption in progress...", ar: "جاري التشفير..." },
  decryptionInProgress: { en: "Decryption in progress...", ar: "جاري فك التشفير..." },
  encryptionSuccess: { en: "File encrypted successfully!", ar: "تم تشفير الملف بنجاح!" },
  decryptionSuccess: { en: "File decrypted successfully!", ar: "تم فك تشفير الملف بنجاح!" },
  encryptionFailed: { en: "Encryption failed.", ar: "فشل التشفير." },
  decryptionFailed: { en: "Decryption failed.", ar: "فشل فك التشفير." },
  fileAlreadyExists: {en: "File already exists. Overwrite?", ar: "الملف موجود بالفعل. هل تريد الكتابة فوقه؟"},
  originalFile: {en: "Original File", ar: "الملف الأصلي"},
  encryptedFile: {en: "Encrypted File", ar: "الملف المشفر"},
  decryptedFile: {en: "Decrypted File", ar: "الملف المفكوك تشفيره"},
  dragDropFile: { en: "Drag & drop a file here, or click to select", ar: "اسحب وأفلت ملفًا هنا، أو انقر للاختيار" },
  dragDropFiles: { en: "Drag & drop files here, or click to select", ar: "اسحب وأفلت ملفات هنا، أو انقر للاختيار" },
  dragDropFolder: { en: "Drag & drop a folder here, or click to select", ar: "اسحب وأفلت مجلدًا هنا، أو انقر للاختيار" },
  dragDropOrClick: { en: "Drag & drop or click to select", ar: "اسحب وأفلت أو انقر للاختيار"},
  maxFileSize: { en: "Max file size", ar: "الحد الأقصى لحجم الملف"},
  processingFile: { en: "Processing file...", ar: "جاري معالجة الملف..."},
  shredOriginalFile: { en: "Securely shred original file after encryption?", ar: "هل تريد حذف الملف الأصلي بأمان بعد التشفير؟" },
  shredEncryptedFile: { en: "Securely shred encrypted file after decryption?", ar: "هل تريد حذف الملف المشفر بأمان بعد فك التشفير؟" },
  important: { en: "Important", ar: "هام" },
  encryptionDisclaimer: { en: "Ensure you use a strong, unique password and store it securely. Lost passwords mean lost data, permanently.", ar: "تأكد من استخدام كلمة مرور قوية وفريدة وتخزينها بأمان. فقدان كلمة المرور يعني فقدان البيانات بشكل دائم." },
  metadataInfo: { en: "Metadata Info", ar: "معلومات البيانات الوصفية" },
  metadataExplanation: { en: "For certain algorithms like AES-GCM, metadata (IV, AuthTag, Salt) is stored with the encrypted file. This is normal and required for decryption. This metadata is not your password.", ar: "لبعض الخوارزميات مثل AES-GCM، يتم تخزين البيانات الوصفية (IV، AuthTag، Salt) مع الملف المشفر. هذا طبيعي ومطلوب لفك التشفير. هذه البيانات الوصفية ليست كلمة مرورك."},
  selectEncryptedFile: { en: "Select Encrypted File (.knxenc, .enc, ...)", ar: "اختر ملفًا مشفرًا (.knxenc, .enc, ...)" },
  selectIfUnknown: { en: "Select if not auto-detected", ar: "اختر إذا لم يتم التعرف عليه تلقائيًا" },
  decryptionDisclaimer: { en: "Correct password and algorithm (plus any required metadata like IV, Salt, AuthTag if not embedded) are essential for successful decryption.", ar: "كلمة المرور الصحيحة والخوارزمية (بالإضافة إلى أي بيانات وصفية مطلوبة مثل IV، Salt، AuthTag إذا لم تكن مضمنة) ضرورية لفك التشفير بنجاح." },
  metadataReminderDecrypt: { en: "If the encrypted file does not internally store metadata (IV, Salt, AuthTag), you might need to provide it. This application will attempt to auto-detect if possible.", ar: "إذا كان الملف المشفر لا يخزن البيانات الوصفية (IV، Salt، AuthTag) داخليًا، فقد تحتاج إلى توفيرها. سيحاول هذا التطبيق التعرف عليها تلقائيًا إذا أمكن." },
  metadataInputNote: { en: "Metadata (IV, Salt, AuthTag) is typically stored with the encrypted file or derived during encryption. Manual input is for advanced cases or specific file formats.", ar: "عادةً ما يتم تخزين البيانات الوصفية (IV، Salt، AuthTag) مع الملف المشفر أو اشتقاقها أثناء التشفير. الإدخال اليدوي للحالات المتقدمة أو تنسيقات ملفات معينة."},
  missingMetadataGCM: { en: "For AES-GCM, IV and AuthTag are required. Please ensure they are loaded or provided.", ar: "بالنسبة لـ AES-GCM، فإن IV و AuthTag مطلوبان. يرجى التأكد من تحميلهما أو توفيرهما."},


  // Algorithm Labels
  algoAES256GCM: { en: "AES-256-GCM (Recommended)", ar: "AES-256-GCM (موصى به)" },
  algoAES512GCM: { en: "AES-512-GCM (Experimental)", ar: "AES-512-GCM (تجريبي)" },
  algoChaCha20Poly1305: { en: "ChaCha20-Poly1305", ar: "ChaCha20-Poly1305" },
  algoNTRU: { en: "NTRU (Post-Quantum)", ar: "NTRU (ما بعد الكم)" },
  algoKyber: { en: "Kyber (Post-Quantum)", ar: "Kyber (ما بعد الكم)" },
  postQuantumWarning: { en: "Post-quantum algorithms are experimental and may have performance implications.", ar: "خوارزميات ما بعد الكم تجريبية وقد تؤثر على الأداء." },

  // Vault Page
  createVault: { en: "Create Vault", ar: "إنشاء خزانة" },
  vaultName: { en: "Vault Name", ar: "اسم الخزانة" },
  selectVaultLocation: { en: "Select Vault Location", ar: "اختر موقع الخزانة" },
  noVaults: { en: "No vaults created yet.", ar: "لم يتم إنشاء خزائن بعد." },
  vaultCreatedSuccess: { en: "Vault created successfully!", ar: "تم إنشاء الخزانة بنجاح!" },
  manageVault: { en: "Manage Vault", ar: "إدارة الخزانة" },
  addFilesToVault: { en: "Add Files to Vault", ar: "إضافة ملفات للخزانة" },
  filesInVault: { en: "Files in Vault", ar: "الملفات في الخزانة" },
  files: {en: "Files", ar: "الملفات"},
  size: {en: "Size", ar: "الحجم"},
  created: {en: "Created", ar: "تاريخ الإنشاء"},
  manageContents: {en: "Manage Contents", ar: "إدارة المحتويات"},
  searchVaults: {en: "Search vaults by name or path...", ar: "ابحث في الخزائن بالاسم أو المسار..."},
  noResultsFound: {en: "No results found.", ar: "لم يتم العثور على نتائج."},
  vaultNameAndPathRequired: {en: "Vault name and path are required.", ar: "اسم الخزانة والمسار مطلوبان."},
  vaultCreationFailed: {en: "Vault creation failed.", ar: "فشل إنشاء الخزانة."},
  confirmDeleteVault: {en: "Are you sure you want to delete this vault? This action cannot be undone.", ar: "هل أنت متأكد أنك تريد حذف هذه الخزانة؟ لا يمكن التراجع عن هذا الإجراء."},
  enterVaultName: {en: "Enter vault name", ar: "أدخل اسم الخزانة"},
  vaultLocation: {en: "Vault Location", ar: "موقع الخزانة"},
  selectVaultLocationPlaceholder: {en: "Click button to select location -->", ar: "انقر على الزر لاختيار الموقع -->"},
  create: {en: "Create", ar: "إنشاء"},
  noFilesFoundInVault: {en: "No files found in this vault or vault is empty.", ar: "لم يتم العثور على ملفات في هذه الخزانة أو أن الخزانة فارغة."},
  vaultContentsDisclaimer: {en: "File operations within vaults (add, decrypt, remove) require Electron backend implementation.", ar: "عمليات الملفات داخل الخزائن (إضافة، فك تشفير، إزالة) تتطلب تنفيذ الواجهة الخلفية لـ Electron."},
  couldNotLoadVaultContents: {en: "Could not load contents for vault '{0}'. See console for details.", ar: "تعذر تحميل محتويات الخزانة '{0}'. راجع وحدة التحكم لمزيد من التفاصيل."},

  // Activity Log Page
  clearLog: { en: "Clear Log", ar: "مسح السجل" },
  logEmpty: { en: "Activity log is empty.", ar: "سجل النشاط فارغ." },
  logEntryDetails: { en: "Details", ar: "التفاصيل" },
  logOperation: {en: "Operation", ar: "العملية"},
  logTimestamp: {en: "Timestamp", ar: "الوقت"},
  searchLogs: { en: "Search logs by operation, details, or target file...", ar: "ابحث في السجلات بالعملية، التفاصيل، أو الملف المستهدف..." },
  filterByStatus: { en: "Filter by status", ar: "تصفية حسب الحالة" },
  all: { en: "All", ar: "الكل" },
  failure: { en: "Failure", ar: "فشل" },
  info: { en: "Info", ar: "معلومات" },
  targetFile: {en: "Target File", ar: "الملف الهدف"},
  app_start: { en: "Application Start", ar: "بدء تشغيل التطبيق"},
  error_generic: { en: "Generic Error", ar: "خطأ عام"},
  login: { en: "User Login", ar: "تسجيل دخول المستخدم"},
  // logout: { en: "User Logout", ar: "تسجيل خروج المستخدم"}, // Already exists for button
  shred: { en: "Shred", ar: "حذف آمن" },
  key_generate: { en: "Key Generation", ar: "إنشاء مفتاح" },
  vault_create: { en: "Vault Creation", ar: "إنشاء خزانة" },
  vault_delete: { en: "Vault Deletion", ar: "حذف خزانة" },
  vault_list_contents: { en: "Vault Contents Listed", ar: "عرض محتويات الخزانة"},
  settings_change: { en: "Settings Change", ar: "تغيير الإعدادات" },

  // Key Generator Page
  generateNewKey: { en: "Generate New Key/Password", ar: "إنشاء مفتاح/كلمة مرور جديدة" },
  passwordLength: { en: "Password Length", ar: "طول كلمة المرور" },
  includeUppercase: { en: "Include Uppercase (A-Z)", ar: "تضمين أحرف كبيرة (A-Z)" },
  includeLowercase: { en: "Include Lowercase (a-z)", ar: "تضمين أحرف صغيرة (a-z)" },
  includeNumbers: { en: "Include Numbers (0-9)", ar: "تضمين أرقام (0-9)" },
  includeSymbols: { en: "Include Symbols (!@#$)", ar: "تضمين رموز (!@#$)" },
  includeUppercaseWithIcon: { en: "ABC", ar: "أبت" },
  includeLowercaseWithIcon: { en: "abc", ar: "أبت (صغيرة)" },
  includeNumbersWithIcon: { en: "123", ar: "١٢٣" },
  includeSymbolsWithIcon: { en: "#$&", ar: "#$&" },
  characterSets: { en: "Character Sets", ar: "مجموعات الأحرف" },
  generatedPassword: { en: "Generated Password:", ar: "كلمة المرور المُنشأة:" },
  copyPassword: { en: "Copy Password", ar: "نسخ كلمة المرور" },
  generate: { en: "Generate", ar: "إنشاء" },
  keyStrength: { en: "Key Strength", ar: "قوة المفتاح"},
  keyStrengthTooShort: { en: "Too Short", ar: "قصير جداً"},
  keyStrengthWeak: { en: "Weak", ar: "ضعيف"},
  keyStrengthModerate: { en: "Moderate", ar: "متوسط"},
  keyStrengthStrong: { en: "Strong", ar: "قوي"},
  keyStrengthVeryStrong: { en: "Very Strong", ar: "قوي جداً"},
  selectAtLeastOneCharType: {en: "Please select at least one character type.", ar: "يرجى اختيار نوع حرف واحد على الأقل."},
  keyGeneratorDisclaimer: {en: "Use these generated keys responsibly. Strong keys are vital for security.", ar: "استخدم هذه المفاتيح المنشأة بمسؤولية. المفاتيح القوية ضرورية للأمان."},
  aiStrengthCheckUsed: { en: "AI Strength Check", ar: "فحص القوة بالذكاء الاصطناعي" },
  localStrengthCheckUsed: { en: "Local Strength Check", ar: "فحص القوة المحلي" },
  aiStrengthCheckUnavailable: { en: "AI check unavailable", ar: "فحص الذكاء الاصطناعي غير متوفر" },

  // Secure Shredder Page
  shredWarning: { en: "WARNING: Shredding a file is irreversible and will permanently delete the data. Proceed with extreme caution.", ar: "تحذير: حذف الملفات بشكل آمن عملية لا رجعة فيها وستؤدي إلى حذف البيانات نهائيًا. تعامل بحذر شديد." },
  selectFileToShred: { en: "Select File to Shred", ar: "اختر ملفًا لحذفه بأمان" },
  shredPasses: { en: "Number of Passes (Overwrites)", ar: "عدد مرات الكتابة فوق الملف" },
  shredFileButton: { en: "Shred File Permanently", ar: "حذف الملف نهائيًا بأمان" },
  shreddingInProgress: { en: "Shredding in progress...", ar: "جاري الحذف الآمن..." },
  shredSuccess: { en: "File shredded successfully!", ar: "تم حذف الملف بأمان!" },
  shredFailed: { en: "Shredding failed.", ar: "فشل الحذف الآمن." },
  shredConfirmPrompt: { en: "Are you absolutely sure you want to shred this file? This action is IRREVERSIBLE and the file will be PERMANENTLY DELETED.", ar: "هل أنت متأكد تمامًا من أنك تريد حذف هذا الملف بشكل آمن؟ هذا الإجراء لا رجعة فيه وسيتم حذف الملف نهائيًا." },
  shredConfirmProceed: { en: "Confirmation checkbox below must be checked to enable shredding.", ar: "يجب تحديد مربع اختيار التأكيد أدناه لتمكين الحذف الآمن." },
  shredPassesInfo: { en: "More passes increase security but take longer. 1-3 passes are generally sufficient for most users.", ar: "المزيد من مرات الكتابة فوق الملف يزيد من الأمان ولكنه يستغرق وقتًا أطول. 1-3 مرات كافية بشكل عام لمعظم المستخدمين." },
  confirmShredAction: { en: "I understand this action is irreversible and will permanently delete the selected file.", ar: "أفهم أن هذا الإجراء لا رجعة فيه وسيحذف الملف المحدد نهائيًا."},

  // Settings Page
  securityPrivacy: { en: "Security & Privacy", ar: "الأمن والخصوصية" },
  appLock: { en: "App Lock (PIN/Password)", ar: "قفل التطبيق (رمز PIN/كلمة مرور)" },
  enableAppLock: { en: "Enable App Lock", ar: "تمكين قفل التطبيق" },
  autoLock: { en: "Auto-lock after inactivity", ar: "قفل تلقائي بعد فترة خمول" },
  defaultAlgorithm: { en: "Default Encryption Algorithm", ar: "خوارزمية التشفير الافتراضية" },
  defaultShredPasses: { en: "Default Shred Passes", ar: "عدد مرات الحذف الافتراضية" },
  deleteOriginalAfterEncryption: { en: "Delete original file after successful encryption by default", ar: "حذف الملف الأصلي تلقائيًا بعد التشفير الناجح" },
  deleteEncryptedAfterDecryption: { en: "Delete encrypted file after successful decryption by default", ar: "حذف الملف المشفر تلقائيًا بعد فك التشفير الناجح" },
  importExportSettings: { en: "Import/Export Settings", ar: "استيراد/تصدير الإعدادات" },
  importSettings: { en: "Import Settings", ar: "استيراد الإعدادات" },
  exportSettings: { en: "Export Settings", ar: "تصدير الإعدادات" },
  privacyPolicy: { en: "Privacy Policy", ar: "سياسة الخصوصية" },
  privacyStatementUltraEncrypt: { en: "KNOUX UltraEncrypt Pro is committed to your privacy. All encryption/decryption operations are performed locally on your device. We do not track your files or passwords. Your data remains under your control.", ar: "KNOUX UltraEncrypt Pro ملتزم بخصوصيتك. جميع عمليات التشفير وفك التشفير تتم محليًا على جهازك. نحن لا نتتبع ملفاتك أو كلمات مرورك. بياناتك تبقى تحت سيطرتك." },

  // Certificate Page
  knouxCertificate: { en: "KNOUX Professional Certificate", ar: "شهادة KNOUX المهنية" },
  developerName: { en: "Eng. Sadek elgazar", ar: "م. صادق الجزار" },
  developerRole: { en: "Developer, Cybersecurity Specialist & AI Solutions Architect", ar: "مطور، متخصص في الأمن السيبراني ومهندس حلول الذكاء الاصطناعي" },
  contactInfo: { en: "Contact Information", ar: "معلومات الاتصال" },
  whatsapp: { en: "WhatsApp", ar: "واتساب" },
  email: { en: "Email", ar: "البريد الإلكتروني" },
  location: { en: "Location", ar: "الموقع" },
  issueDate: { en: "Issue Date", ar: "تاريخ الإصدار" },
  digitalSignature: { en: "Digital Signature", ar: "التوقيع الرقمي" },
  exportPdf: { en: "Export as PDF", ar: "تصدير كـ PDF" },
  exportPng: { en: "Export as PNG", ar: "تصدير كـ PNG" },

  // Placeholder for Dashboard page
  welcomeToKnouxUltraEncrypt: { en: "Welcome to KNOUX UltraEncrypt Pro", ar: "مرحبًا بك في KNOUX للتشفير الآمن برو" },
  quickActions: { en: "Quick Actions", ar: "إجراءات سريعة" },
  recentActivity: { en: "Recent Activity", ar: "النشاط الأخير" },
  vaultSummary: { en: "Vault Summary", ar: "ملخص الخزائن" },
  systemStatus: { en: "System Status", ar: "حالة النظام" },
  allSystemsNominal: { en: "All systems nominal. Ready to secure your data.", ar: "جميع الأنظمة تعمل بشكل طبيعي. جاهز لتأمين بياناتك."},

  // Documentation Page
  docSubtitle: { en: "Your comprehensive guide to KNOUX UltraEncrypt Pro.", ar: "دليلك الشامل لـ KNOUX UltraEncrypt Pro." },
  docIntroTitle: { en: "Introduction", ar: "مقدمة" },
  docIntroContent: { en: "Welcome to KNOUX UltraEncrypt Pro, your trusted partner for local file encryption and data security. (TODO: Expand with overview, mission, and key benefits.)", ar: "مرحبًا بك في KNOUX UltraEncrypt Pro، شريكك الموثوق به لتشفير الملفات المحلي وأمن البيانات. (TODO: توسيع مع نظرة عامة، المهمة، والفوائد الرئيسية.)" },
  docEncryptionTitle: { en: "Encryption Guide", ar: "دليل التشفير" },
  docEncryptionContent: { en: "Learn how to encrypt your files and folders securely. (TODO: Detailed steps: selecting files, choosing algorithm, password best practices, understanding output, what happens to original file if 'shred' is selected, common errors.)", ar: "تعلم كيفية تشفير ملفاتك ومجلداتك بأمان. (TODO: خطوات مفصلة: اختيار الملفات، اختيار الخوارزمية، أفضل ممارسات كلمة المرور، فهم الإخراج، ماذا يحدث للملف الأصلي، الأخطاء الشائعة.)" },
  docAlgoAES: {en: "AES-256-GCM", ar: "AES-256-GCM"},
  docAlgoAESDetail: {en: "Industry-standard strong encryption. Recommended for most users. (TODO: Explain GCM, IVs, AuthTags simply.)", ar: "تشفير قوي بمعايير الصناعة. موصى به لمعظم المستخدمين. (TODO: شرح GCM، IVs، AuthTags ببساطة.)"},
  docAlgoChaCha: {en: "ChaCha20-Poly1305", ar: "ChaCha20-Poly1305"},
  docAlgoChaChaDetail: {en: "Modern, fast, and secure stream cipher. (TODO: Briefly explain benefits.)", ar: "شيفرة دفق حديثة وسريعة وآمنة. (TODO: شرح الفوائد بإيجاز.)"},
  docAlgoPQ: {en: "Post-Quantum Cryptography (NTRU, Kyber)", ar: "تشفير ما بعد الكم (NTRU، Kyber)"},
  docAlgoPQDetail: {en: "Experimental algorithms for future-proofing against quantum computers. Use with understanding. (TODO: Explain implications, when to consider.)", ar: "خوارزميات تجريبية للحماية المستقبلية ضد الحواسيب الكمومية. استخدمها بفهم. (TODO: شرح التبعات، متى يجب النظر فيها.)"},
  docDecryptionTitle: { en: "Decryption Guide", ar: "دليل فك التشفير" },
  docDecryptionContent: { en: "How to decrypt your files with the correct password and settings. (TODO: Step-by-step guide, handling metadata if separate, common issues.)", ar: "كيفية فك تشفير ملفاتك بكلمة المرور والإعدادات الصحيحة. (TODO: دليل خطوة بخطوة، التعامل مع البيانات الوصفية إذا كانت منفصلة، المشكلات الشائعة.)" },
  docVaultsTitle: { en: "Managing Vaults", ar: "إدارة الخزائن" },
  docVaultsContent: { en: "Create and manage secure vaults for your encrypted files. (TODO: Explain vault concept, how to create, add files, decrypt from vault, security of vaults.)", ar: "إنشاء وإدارة خزائن آمنة لملفاتك المشفرة. (TODO: شرح مفهوم الخزانة، كيفية الإنشاء، إضافة الملفات، فك التشفير من الخزانة، أمان الخزائن.)" },
  docKeyGenTitle: { en: "Key Generator", ar: "مولد المفاتيح" },
  docKeyGenContent: { en: "Generate strong, random passwords for your encryption needs. (TODO: Explain options, importance of randomness, how strength is estimated.)", ar: "إنشاء كلمات مرور قوية وعشوائية لاحتياجات التشفير الخاصة بك. (TODO: شرح الخيارات، أهمية العشوائية، كيفية تقدير القوة.)" },
  docShredderTitle: { en: "Secure Shredder", ar: "الحذف الآمن" },
  docShredderContent: { en: "Permanently delete files with the secure shredder. (TODO: Explain how it works, importance of passes, when to use it.)", ar: "حذف الملفات نهائيًا باستخدام الحذف الآمن. (TODO: شرح كيفية عمله، أهمية عدد مرات الكتابة، متى يجب استخدامه.)" },
  docSettingsTitle: { en: "Application Settings", ar: "إعدادات التطبيق" },
  docSettingsContent: { en: "Customize themes, language, and default behaviors. (TODO: Detail each setting and its impact.)", ar: "تخصيص المظاهر واللغة والسلوكيات الافتراضية. (TODO: تفصيل كل إعداد وتأثيره.)" },
  docTroubleshootingTitle: { en: "Troubleshooting & FAQ", ar: "استكشاف الأخطاء وإصلاحها والأسئلة الشائعة" },
  docTroubleshootingContent: { en: "Find solutions to common issues and answers to frequently asked questions. (TODO: Populate with common errors, user questions, and solutions.)", ar: "ابحث عن حلول للمشكلات الشائعة وإجابات للأسئلة المتداولة. (TODO: ملء بالأخطاء الشائعة، أسئلة المستخدمين، والحلول.)" },
  docContactTitle: {en: "Contact & Support", ar: "الاتصال والدعم"},
  docContactContent: {en: "How to reach out for support or provide feedback. (TODO: Provide contact methods from constants or a dedicated form if planned.)", ar: "كيفية التواصل للحصول على الدعم أو تقديم ملاحظات. (TODO: توفير طرق الاتصال من الثوابت أو نموذج مخصص إذا كان مخططًا له.)"},
  needMoreHelp: { en: "Need More Help?", ar: "هل تحتاج إلى مزيد من المساعدة؟" },
  contactSupportMessage: { en: "If you can't find an answer here, please don't hesitate to contact support.", ar: "إذا لم تتمكن من العثور على إجابة هنا، فلا تتردد في الاتصال بالدعم." }
};